name: docfx

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Setup docfx
      run: dotnet tool update -g docfx
    - name: Copy README
      run: cp README.md "./src/wan24-Crypto-NaCl Docs/index.md"
    - name: Build docs
      run: docfx "./src/wan24-Crypto-NaCl Docs/docfx.json" -t default,templates/singulinkfx
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
